config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #microbreweries
  get '/microbreweries', to: 'microbreweries#index'
  get '/microbreweries/new', to: 'microberbeers#index'
  post '/microbreweries', to: 'microbreweries#create'
  get '/microbreweries/:id/beers', to: 'microbrewerybeers#index' #, as: 'microbrewerybeersindex'
  get '/microbreweries/:id', to: 'microbreweries#show'
  get '/microbreweries/:id/edit', to: 'microbreweries#edit'
  patch '/microbreweries/:id', to: 'microbreweries#update'
  post '/microbreweries/:id', to: 'microbreweries#update'
  delete 'microbreweries/:id', to: 'microbreweries#destroy'

  get 'microbreweries/:id/beers/new', to: 'microbrewerybeers#new'
  post 'microbreweries/:id/beers/', to: 'microbrewerybeers#create'

  #beer
  get '/beers', to: 'beers#index'
  get '/beers/:id', to: 'beers#show'
  get '/beers/:id/edit', to: 'beers#edit'
  patch '/beers/:id', to: 'beers#update'
  post '/beers/:id', to: 'beers#create'
  delete '/beers/:id', to: 'beers#destroy'

  #teahouses
  get '/teahouses', to: 'teahouses#index'
  get '/teahouses/:id/teas', to: 'teahouseteas#index', as: 'teahouseteasindex'
  get 'teahouses/new', to: 'teahouses#new'
  post '/teahouses', to: 'teahouses#create'
  get '/teahouses/:id', to: 'teahouses#show'
  get '/teahouses/:id/edit', to: 'teahouses#edit'
  patch '/teahouses/:id', to: 'teahouses#update'
  post '/teahouses/:id', to: 'teahouses#update'
  get '/teahouses/:id/teas/edit', to: 'teahouseteas#edit', as: 'teahouseteasedit'
  patch '/teahouses/:id/teas', to: 'teahouseteas#update'
  post '/teahouses/:id/teas', to: 'teahouseteas#update'
  delete 'teahouses/:id', to: 'teahouses#destroy'

  #teas
  get '/teas', to: 'teas#index'
  get '/teas/:id', to: 'teas#show'
  get '/teas/:id/edit', to: 'teas#edit'
  patch '/teas/:id', to: 'teas#update'
  post '/teas/:id', to: 'teas#update'
  delete 'teas/:id', to: 'teas#destroy'

  #teahouseteas
  get '/teahouseteas/:id/teas', to: 'teahouseteas#index', as: 'teahouseteas'
  get '/teahouses/:id/teas/new', to: 'teahouseteas#new'
  post '/teahouses/:id/teas', to: 'teahouseteas#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :microbrewery

  def self.new_beers
    order("brewed_on desc")
  end

  def self.happy_level(threshold)
    where("ABV >= #{threshold}")
  end

end

app/models/microbrewery.rb
class Microbrewery < ApplicationRecord
  has_many :beers, dependent: :destroy

  def self.outdoor_seating
    order("outdoor_seating desc")
  end

end

app/models/tea.rb
class Tea < ApplicationRecord
  belongs_to :teahouse

  def self.count_teas
    count
  end

  def self.caffeinated
    order("caffeinated desc")
  end
  
  def self.grams_required(threshold)
    where("grams_needed >= #{threshold}")
  end

  def self.order_by_alphabet
    order("name asc")
  end
  
end

app/models/teahouse.rb
class Teahouse < ApplicationRecord
  has_many :teas, dependent: :destroy

  def self.order_by_opening_date
    order("opening_date desc")
  end

  def self.order_by_count
    select("teahouses.*, count(teas) as tea_count")
      .joins(:teas)
      .group(:id)
      .order("tea_count desc")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    if params[:threshold]
      require "pry"; binding.pry
      @beers = Beer.happy_level(params[:threshold])
    else
      @beers = Beer.order("brewed_on desc")
    end
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    beer = Beer.find(params[:id])
    beer.update(beer_params)
    beer.save
    redirect_to "/beers/#{params[:id]}"
  end

  def destroy
    Beer.destroy(params[:id])
    redirect_to '/beers'
  end



  private
  def beer_params
    params.permit(:category, :name, :ABV, :ideal_vessel, :body, :aroma, :color, :brewed_on)
  end
end

app/controllers/microbreweries_controller.rb
class MicrobreweriesController < ApplicationController
  def index
    @microbreweries = Microbrewery.outdoor_seating
  end

  def show
    @microbrewery = Microbrewery.find(params[:id])
  end

  def new
  end

  def create
    microbrewery = Microbrewery.new(brewery_params)
    microbrewery.save
    redirect_to '/microbreweries'
  end

  def edit
    @microbrewery = Microbrewery.find(params[:id])
  end

  def update
    microbrewery = Microbrewery.find(params[:id])
    microbrewery.update(brewery_params)
    microbrewery.save
    redirect_to "/microbreweries/#{microbrewery.id}"
  end

  def destroy
    Microbrewery.destroy(params[:id])
    redirect_to '/microbreweries'
  end

  private
  def brewery_params
    params.permit(:name, :location, :license_renewal, :outdoor_seating, :social_distancing)
  end
end

app/controllers/microbrewerybeers_controller.rb
class MicrobrewerybeersController < ApplicationController
  def index
    @microbrewery_beers = Beer.all
    @microbrewery = Microbrewery.find(params[:id])
  end

  def new
    @microbrewery = Microbrewery.find(params[:id])
  end

  def create
    @microbrewery = Microbrewery.find(params[:id])
    @microbrewery.beers.create!(beer_params)
    redirect_to "/microbreweries/#{params[:id]}/beers"
  end

  private
  def beer_params
    params.permit(:category, :name, :ABV, :ideal_vessel, :body, :aroma, :color, :brewed_on)
  end
end

app/controllers/teahouses_controller.rb
class TeahousesController < ApplicationController

  def index
    if params[:sort]
      @teahouse = Teahouse.order_by_count
    else
      @teahouse = Teahouse.order_by_opening_date
    end
  end

  def show
    @teahouse = Teahouse.find(params[:id])
  end

  def new

  end

  def create
    @teahouse = Teahouse.new(house_params)
    @teahouse.save
    redirect_to '/teahouses'
  end

  def edit
    @teahouse = Teahouse.find(params[:id])
  end

  def update
    teahouse = Teahouse.find(params[:id])
    teahouse.update(house_params)
    teahouse.save
    redirect_to "/teahouses/#{teahouse.id}"
  end

  def destroy
    Teahouse.destroy(params[:id])
    redirect_to '/teahouses'
  end

  private
  def house_params
    params.permit(:name, :location, :restocked_on, :opening_date, :allows_dogs)
  end
end

app/controllers/teahouseteas_controller.rb
class TeahouseteasController < ApplicationController

  def index
    if params[:sort]
      @teahouse_teas = Teahouse.find(params[:id]).teas.order_by_alphabet
      @teahouse = Teahouse.find(params[:id])
    else
      @teahouse_teas = Teahouse.find(params[:id]).teas
      @teahouse = Teahouse.find(params[:id])
    end
  end

  def create
    @teahouse = Teahouse.find(params[:id])
    @teahouse.teas.create!(tea_params)
    redirect_to "/teahouses/#{params[:id]}/teas"
  end

  def new
    @teahouse = Teahouse.find(params[:id])
  end

  def show
    @teas = Tea.find(params[:id])
  end

  def edit
    @teahouse = Teahouse.find(params[:id])
  end

  def update
    tea = Tea.find(params[:tea_id])
    tea.update(tea_params)
    tea.save
    redirect_to 'teahouseteasindex_path'
  end

  private
  def tea_params
    params.permit(:name, :category, :origin, :grams_needed, :steep_time, :brew_temp, :number_of_infusions, :season_picked, :ideal_teapot, :caffeinated)
  end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController

  def index
    if params[:threshold] 
      @teas = Tea.grams_required(params[:threshold])
    else
      @teas = Tea.caffeinated
    end
  end

  def edit
    @tea = Tea.find(params[:id])
  end

  def show
    @tea = Tea.find(params[:id])
  end

  def update
    tea = Tea.find(params[:id])
    tea.update(tea_params)
    tea.save
    redirect_to "/teas"
  end

  def destroy
    tea = Tea.destroy(params[:id])
    redirect_to "/teas"
  end

  private
  def tea_params
    params.permit(:name, :category, :origin, :grams_needed, :steep_time, :brew_temp, :number_of_infusions, :season_picked, :ideal_teapot, :caffeinated)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/edit.html.erb
<%= form_tag "/beers/#{@beer.id}", method: :patch do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name, @beer.name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category, @beer.category %><br>
  <%= label_tag :ABV %><br>
  <%= text_field_tag :ABV, @beer.ABV %><br>
  <%= label_tag :ideal_vessel %><br>
  <%= text_field_tag :ideal_vessel, @beer.ideal_vessel %><br>
  <%= label_tag :body %><br>
  <%= text_field_tag :body, @beer.body %><br>
  <%= label_tag :aroma %><br>
  <%= text_field_tag :aroma, @beer.aroma %><br>
  <%= label_tag :color %><br>
  <%= text_field_tag :color, @beer.color %><br>
  <%= label_tag :brewed_on %><br>
  <%= date_field_tag :brewed_on %><br>
  <%= submit_tag 'Update' %>
<% end %>

app/views/beers/index.html.erb
<h1>Hey Beer Nerd!</h1>

<%= form_tag "/beers", method: :get do %>
  <%= label_tag :how_happy_you_gon_be_enter_ABV_percentage %>
  <%= text_field_tag :threshold %>
  <%= submit_tag 'Get Happy' %>
<% end %>
<h2>Beer Facts:</h2>
<% @beers.each do |beer| %>
  <l1><b><%= beer.name %></b></l1>
  <li>Category: <%= beer.category %></li>
  <li>ABV: <%= beer.ABV %></li>
  <li>Ideal Vessel: <%= beer.ideal_vessel %></li>
  <li>Body: <%= beer.body %></li>
  <li>Aroma: <%= beer.aroma %></li>
  <li>Color: <%= beer.color %></li>
  <li>Brew Date: <%= beer.brewed_on %></li><br>

  <form action="beers/<%= beer.id %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="delete"/>
  </form>

<% end %>

app/views/beers/show.html.erb
<h1><%= @beer.name %> Beer Facts:</h1>

<l1><b><%= @beer.name %></b></l1>
<li>Category: <%= @beer.category %></li>
<li>ABV: <%= @beer.ABV %></li>
<li>Ideal Vessel: <%= @beer.ideal_vessel %></li>
<li>Body: <%= @beer.body %></li>
<li>Aroma: <%= @beer.aroma %></li>
<li>Color: <%= @beer.color %></li>
<li>Brew Date: <%= @beer.brewed_on %></li><br>

<%= link_to "Update Beer", "/beers/#{@beer.id}/edit", method: :get %>

app/views/microbreweries/edit.html.erb
<h3>Edit:</h3>
<%= form_tag("/microbreweries/#{@microbrewery.id}", :method => "post") do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :location %><br>
  <%= text_field_tag :location %><br>
  <%= label_tag :license_renewal %><br>
  <%= date_field_tag :license_renewal, :date %><br>
  <%= label_tag :outdoor_seating %>
  <%= hidden_field_tag :outdoor_seating, false %>
  <%= check_box_tag :outdoor_seating, true %><br>
  <%= label_tag :social_distancing %>
  <%= hidden_field_tag :social_distancing, false %>
  <%= check_box_tag :social_distancing, true %><br>
  <%= submit_tag 'Submit' %>
<% end %>

app/views/microbreweries/index.html.erb
<h1>Kia Ora, whanua! Keen for a beer?</h1>

<h2>Pick your watering hole:</h2>
<% @microbreweries.each do |microbrewery| %>
  <li><a href="/microbreweries/<%= microbrewery.id %>"><%= microbrewery.name %></a></li>
    <li>Outdoor Seating: <%= microbrewery.outdoor_seating %></li>
    <form action="/microbreweries/<%= microbrewery.id %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="delete"/>
  </form>
<% end %>
<h4><a href="/microbreweries/new">New Brewery</a></h4>

app/views/microbreweries/new.html.erb
<h3>What's your new brewery, mate:</h3>

<%= form_tag("/microbreweries", :method => "post") do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :location %><br>
  <%= text_field_tag :location %><br>
  <%= label_tag :license_renewal %><br>
  <%= date_field_tag :license_renewal, :date %><br>
  <%= label_tag :outdoor_seating %>
  <%= hidden_field_tag :outdoor_seating, false %>
  <%= check_box_tag :outdoor_seating, true %><br>
  <%= label_tag :social_distancing %>
  <%= hidden_field_tag :social_distancing, false %>
  <%= check_box_tag :social_distancing, true %><br>
  <%= submit_tag 'Submit' %>
<% end %>

app/views/microbreweries/show.html.erb
<a href="/microbreweries">Brewery Index</a>
<h1>Welcome to <%= @microbrewery.name %>!</h1>
<p><b>Location: </b><%= @microbrewery.location %></p>
<p><b>License Renewal Date: </b><%= @microbrewery.license_renewal %></p>
<p><b>Offers Outdoor Seating: </b><%= @microbrewery.outdoor_seating %></p>
<p><b>Social Distancing: </b><%= @microbrewery.social_distancing %></p><br>

<%= link_to "Update", "/microbreweries/#{@microbrewery.id}/edit", method: :edit %>

app/views/microbrewerybeers/index.html.erb
<h1><%= @microbrewery.name %> Tea List:</h1>
<h2><%= @microbrewery_beers.count %></h2>

<% @microbrewery_beers.each do |beer| %>
  <h3>Name: <%= beer.name %></h3>
  <li>Category: <%= beer.category %></li>
  <li>ABV: <%= beer.ABV %></li>
  <li>Ideal Vessel: <%= beer.ideal_vessel %></li>
  <li>Body:<%= beer.body %></li>
  <li>Aroma: <%= beer.aroma %></li>
  <li>Color: <%= beer.color %></li>
  <li>Brewed On: <%= beer.brewed_on %></li>
<% end %>

<%= link_to "Add New Beer", "/microbreweries/#{@microbrewery.id}/beers/new", method: :get %><br>

app/views/microbrewerybeers/new.html.erb
<h3>What's your new brew, friend?</h3>

<%= form_tag("/microbreweries/#{@microbrewery.id}/beers", method: :post) do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category %><br>
  <%= label_tag :ABV %><br>
  <%= text_field_tag :ABV %><br>
  <%= label_tag :ideal_vessel %><br>
  <%= text_field_tag :ideal_vessel %><br>
  <%= label_tag :body %><br>
  <%= text_field_tag :body %><br>
  <%= label_tag :aroma %><br>
  <%= text_field_tag :aroma %><br>
  <%= label_tag :color %><br>
  <%= text_field_tag :color %><br>
  <%= label_tag :brewed_on %><br>
  <%= date_field_tag :brewed_on %><br>
  <%= submit_tag 'Create' %>
<% end %>

app/views/teahouses/edit.html.erb
<h3>Edit <%= @teahouse.name %></h3>

<%= form_tag("/teahouses/#{@teahouse.id}", :method => "post") do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :location %><br>
  <%= text_field_tag :location %><br>
  <%= label_tag :restocked_on %><br>
  <%= date_field_tag :restocked_on, :date %><br>
  <%= label_tag :opening_date %><br>
  <%= date_field_tag :opening_date, :date %><br>
  <%= label_tag :allows_dogs %>
  <%= hidden_field_tag :allows_dogs, false %>
  <%= check_box_tag :allows_dogs, true %><br>
  <%= submit_tag 'Submit'%>
<% end %>

app/views/teahouses/index.html.erb
<h1>Hey, hey! Welcome to the tea lounge.</h1>

<h2>Where shall we have our cuppa tea today?</h2>

<% @teahouse.each do |tea_house| %>
  <h3><li><a href="/teahouses/<%= tea_house.id %>"><%= tea_house.name %></a></li></h3>
  <p><b>Opening Date: </b><%= tea_house.opening_date %></p>
  <p><b>Count Of Teas In Stock: </b><%= tea_house.teas.count_teas %></p>
  <h5><%= link_to "Update Teahouse Info", "/teahouses/#{tea_house.id}/edit", method: :get %></h5>
  <form action="teahouses/<%= tea_house.id %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="delete"/>
  </form>
<% end %>

<h4><%= link_to "Sort By Highest to Lowest Stocked Teas", teahouses_path(sort: :true), method: :get %><br></h4>
<h4><a href="/teahouses/new">New Tea House</a></h4>

app/views/teahouses/new.html.erb
<h3>What's your new brewing sanctuary?</h3>

<%= form_tag("/teahouses", :method => "post") do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :location %><br>
  <%= text_field_tag :location %><br>
  <%= label_tag :restocked_on %><br>
  <%= date_field_tag :restocked_on, :date %><br>
  <%= label_tag :opening_date %><br>
  <%= date_field_tag :opening_date, :date %><br>
  <%= label_tag :allows_dogs %>
  <%= hidden_field_tag :allows_dogs, false %>
  <%= check_box_tag :allows_dogs, true %><br>
  <%= submit_tag 'Submit'%>
<% end %>

app/views/teahouses/show.html.erb
<a href="/teahouses">Tea House Index</a>
<h2>Welcome to <%=  @teahouse.name %>!</h2>
<p><b>Location: </b><%= @teahouse.location %></p>
<p><b>Restocked On: </b><%= @teahouse.restocked_on %></p>
<p><b>Opening Date: </b><%= @teahouse.opening_date %></p>
<p><b>Dogs Permitted: </b><%= @teahouse.allows_dogs %></p><br>

<%= link_to "Stocked Teas", "/teahouses/#{@teahouse.id}/teas", method: :show %><br>
<%= link_to "Update Teahouse", "/teahouses/#{@teahouse.id}/edit", method: :edit %>

app/views/teahouseteas/edit.html.erb
<h3>What's different friend?</h3>

<%= form_tag("/teahouses/#{@teahouse.id}/teas", method: :patch) do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category %><br>
  <%= label_tag :origin %><br>
  <%= text_field_tag :origin %><br>
  <%= label_tag :grams_needed %><br>
  <%= number_field_tag :grams_needed %><br>
  <%= label_tag :steep_time %><br>
  <%= number_field_tag :steep_time %><br>
  <%= label_tag :brew_temp %><br>
  <%= number_field_tag :brew_temp %><br>
  <%= label_tag :number_of_infusions %><br>
  <%= number_field_tag :number_of_infusions %><br>
  <%= label_tag :season_picked %><br>
  <%= date_field_tag :season_picked %><br>
  <%= label_tag :ideal_teapot %><br>
  <%= text_field_tag :ideal_teapot %><br>
  <%= label_tag :caffeinated %>
  <%= hidden_field_tag :caffeinated, false %>
  <%= check_box_tag :caffeinated, true %><br>
  <%= submit_tag 'Update' %>
<% end %>

app/views/teahouseteas/index.html.erb
<h1><%= @teahouse.name %> Tea List:</h1>
<h2><%= @teahouse_teas.count_teas %> Total Teas</h2>

<% @teahouse_teas.each do |tea| %>
  <h3>Name: <%= tea.name %></h3>
  <li>Category: <%= tea.category %></li>
  <li>Origin: <%= tea.origin %></li>
  <li>Grams Needed: <%= tea.grams_needed %></li>
  <li>Steep Time:<%= tea.steep_time %></li>
  <li>Brew Temp: <%= tea.brew_temp %></li>
  <li>Number of Infusions: <%= tea.number_of_infusions %></li>
  <li>Season Picked: <%= tea.season_picked %></li>
  <li>Ideal Teapot: <%= tea.ideal_teapot %></li>
  <li>Caffinated? <%= tea.caffeinated %></li><br/>
  <%= link_to "Update Tea", teahouseteasedit_path(:tea_id => tea.id), method: :get %><br>
<% end %>
<h4><%= link_to "Sort Teas Alphabetically", teahouseteas_path(sort: :true), method: :get %></h4>
<% binding.pry %>
<%= link_to "Add New Tea", "/teahouses/#{@teahouse.id}/teas/new", method: :get %><br>

<%= link_to "Take Me Back", "/teahouses/#{@teahouse.id}", method: :get %><br>

app/views/teahouseteas/new.html.erb
<h3>What's your new brew, friend?</h3>

<%= form_tag("/teahouses/#{@teahouse.id}/teas", method: :post) do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category %><br>
  <%= label_tag :origin %><br>
  <%= text_field_tag :origin %><br>
  <%= label_tag :grams_needed %><br>
  <%= number_field_tag :grams_needed %><br>
  <%= label_tag :steep_time %><br>
  <%= number_field_tag :steep_time %><br>
  <%= label_tag :brew_temp %><br>
  <%= number_field_tag :brew_temp %><br>
  <%= label_tag :number_of_infusions %><br>
  <%= number_field_tag :number_of_infusions %><br>
  <%= label_tag :season_picked %><br>
  <%= date_field_tag :season_picked %><br>
  <%= label_tag :ideal_teapot %><br>
  <%= text_field_tag :ideal_teapot %><br>
  <%= label_tag :caffeinated %>
  <%= hidden_field_tag :caffeinated, false %>
  <%= check_box_tag :caffeinated, true %><br>
  <%= submit_tag 'Create' %>
<% end %>

app/views/teas/edit.html.erb
<h3>What's different friend?</h3>

<%= form_tag("/teas/#{@tea.id}", method: :patch) do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category %><br>
  <%= label_tag :origin %><br>
  <%= text_field_tag :origin %><br>
  <%= label_tag :grams_needed %><br>
  <%= number_field_tag :grams_needed %><br>
  <%= label_tag :steep_time %><br>
  <%= number_field_tag :steep_time %><br>
  <%= label_tag :brew_temp %><br>
  <%= number_field_tag :brew_temp %><br>
  <%= label_tag :number_of_infusions %><br>
  <%= number_field_tag :number_of_infusions %><br>
  <%= label_tag :season_picked %><br>
  <%= date_field_tag :season_picked %><br>
  <%= label_tag :ideal_teapot %><br>
  <%= text_field_tag :ideal_teapot %><br>
  <%= label_tag :caffeinated %>
  <%= hidden_field_tag :caffeinated, false %>
  <%= check_box_tag :caffeinated, true %><br>
  <%= submit_tag 'Update' %>
<% end %>

app/views/teas/index.html.erb
<h1>Tea List:</h1>

<%= form_tag "/teas", method: :get do %>
  <%= label_tag :desired_weight %><br>
  <%= text_field_tag :threshold %><br>
  <%= submit_tag 'Get Results' %>
<% end %>
<% @teas.each do |tea| %>
  <a href="/teas/<%= tea.id %>"><h3><%= tea.name %></h3></a>
  <li><b>Caffinated? </b><%= tea.caffeinated %></li><br>
  <li>Category: <%= tea.category %></li>
  <li>Origin: <%= tea.origin %></li>
  <li>Grams Needed: <%= tea.grams_needed %></li>
  <li>Steep Time:<%= tea.steep_time %></li>
  <li>Brew Temp: <%= tea.brew_temp %></li>
  <li>Number of Infusions: <%= tea.number_of_infusions %></li>
  <li>Ideal Teapot: <%= tea.ideal_teapot %></li>
  <li>Season Picked: <%= tea.season_picked %></li><br/>
  <%= link_to "Update Tea", "/teas/#{tea.id}/edit", method: :get %><br>
  <form action="teas/<%= tea.id %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="delete"/>
  </form>
<% end %>

app/views/teas/new.html.erb
<h3>What's your new brew, friend?</h3>

<%= form_tag("/teahouses/:id/teas", method: :post) do %>
  <%= label_tag :name %><br>
  <%= text_field_tag :name %><br>
  <%= label_tag :category %><br>
  <%= text_field_tag :category %><br>
  <%= label_tag :origin %><br>
  <%= text_field_tag :origin %><br>
  <%= label_tag :grams_needed %><br>
  <%= number_field_tag :grams_needed %><br>
  <%= label_tag :steep_time %><br>
  <%= number_field_tag :steep_time %><br>
  <%= label_tag :brew_temp %><br>
  <%= number_field_tag :brew_temp %><br>
  <%= label_tag :number_of_infusions %><br>
  <%= number_field_tag :number_of_infusions %><br>
  <%= label_tag :season_picked %><br>
  <%= date_field_tag :season_picked %><br>
  <%= label_tag :ideal_teapot %><br>
  <%= text_field_tag :ideal_teapot %><br>
  <%= label_tag :caffeinated %>
  <%= hidden_field_tag :caffeinated, false %>
  <%= check_box_tag :caffeinated, true %><br>
  <%= submit_tag 'Create' %>
<% end %>

app/views/teas/show.html.erb
<h1><%= @tea.name %> Tea Attributes:</h1>

  <h3>Name: <%= @tea.name %></h3>
  <li>Category: <%= @tea.category %></li>
  <li>Origin: <%= @tea.origin %></li>
  <li>Grams Needed: <%= @tea.grams_needed %></li>
  <li>Steep Time:<%= @tea.steep_time %></li>
  <li>Brew Temp: <%= @tea.brew_temp %></li>
  <li>Number of Infusions: <%= @tea.number_of_infusions %></li>
  <li>Season Picked: <%= @tea.season_picked %></li>
  <li>Ideal Teapot: <%= @tea.ideal_teapot %></li>
  <li>Caffinated? <%= @tea.caffeinated %></li><br/>
  <%= link_to "Update Tea", "/teas/#{@tea.id}/edit", method: :get %>
  <%= button_to "Delete Tea", "/teas/#{@tea.id}", method: :delete %>